name: Pipeline Bug Report
description: >-
  매크로가 멈춰버리거나 이상한 행동을 하거나 무한반복 하는 경우 골라주세요.
labels: ["Issue-Bug", "Area-Pipeline"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: |
        이슈 올리기 전에 한번만 확인 부탁드립니다.
      options:
        - label: >-
            버그가 한 번만 발생하지 않고, 재현 가능합니다.
          required: true
        - label: >-
            [설명서](docs/USAGE.md)대로 설정을 완료했으며, FAQ를 읽어봤습니다.
          required: true
        - label: >-
            최신 릴리즈에서 발생하는 이슈입니다.
          required: true
        - label: >-
            이미 동일한 내용이 올라온 다른 이슈가 없습니다.
          required: true
  - type: textarea
    id: describe
    attributes:
      label: Description
      description: 버그가 발생하는 상황과 버그 내용에 대한 자세한 설명을 적어주세요.
    validations:
      required: true
  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: 버그 빈도를 골라주세요.
      multiple: false
      options:
        - 항상 발생
        - 항상 발생하지는 않으나, 가끔 발생함
        - 렉문제 (1배럭일때 발생하지는 않으나, 배럭 수를 늘리면 발생함)
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: Configuration information
      description: >-
        사용하는 환경을 최대한 자세하게 적어주세요.

        1. OS, OS 버전

        2. MaaReroll 실행방법 (CLI의 경우 MaaPiCli, GUI의 경우 MAAvalonia)

        3. 앱플레이어, 앱플레이어 버전, 앱플레이어 설정 (DPI, FPS 등등)

        [설명서](docs/USAGE.md)에서 사용하는 MuMuPlayer와 설정이 똑같다면 "MuMuPlayer 기본 설정 사용중"이라고 적어주셔도 됩니다.
      value: >-
        OS: Windows  


        Interface: MAAvalonia  


        Emulator: MuMuPlayer 기본 설정 사용중
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or recordings
      description: 버그와 관련된 스크린샷이나 녹화 영상을 올려주시면 도움이 정말 많이 됩니다.
      placeholder: |
        여기에 파일들을 올려주세요.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log and config files
      description: >-
        **MaaReroll을 종료한 후**, 아래 파일들을 올려주시면 도움이 많이 됩니다.

        1. `debug/maa.log`, `debug/maa.bak.log` 파일 (버그가 발생한 시간도 적어주시면 더 좋습니다.)

        2. `config/maa_pi_config.json`, `config/maa_option.json` 파일
      placeholder: |
        반드시 MaaReroll을 종료한 후 파일들을 올려주세요.
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: Anything else?
      description: |
        추가로 하고 싶은 말이 있다면 적어주세요.
    validations:
      required: false