name: Feature Request
description: >-
  새로운 기능이나 개선사항을 제안하고 싶을 때 골라주세요.
labels: ["Issue-Enhancement"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: |
        이슈 올리기 전에 한번만 확인 부탁드립니다.
      options:
        - label: >-
            이미 동일한 내용이 올라온 다른 이슈가 없습니다.
          required: true
  - type: textarea
    id: describe
    attributes:
      label: Description
      description: 새로운 기능/개선사항과 그 필요성에 대해 적어주세요.
    validations:
      required: false
  - type: textarea
    id: proposal
    attributes:
      label: Any good ideas?
      description: 새로운 기능/개선사항에 대한 자세한 설명을 적어주세요.
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: Anything else?
      description: |
        추가로 하고 싶은 말이 있다면 적어주세요.
    validations:
      required: false